const BILIBILI_DYNAMIC_URL = "https://t.bilibili.com"
const BILIBILI_DYNAMIC_DETAIL_URL = "https://www.bilibili.com/opus"
const BILIBILI_SPACE_URL = "https://space.bilibili.com"
const BILIBILI_SEARCH_URL = "https://search.bilibili.com"
const BILIBILI_POPULAR_URL = "https://www.bilibili.com/v/popular"
const BILIBILI_VIDEO_URL = "https://www.bilibili.com/video"
const BILIBILI_WATCH_LATER_URL = "https://www.bilibili.com/list/watchlater"
